name: Lint

on: [pull_request]

jobs:
  squash:
    name: Check commits count
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check commits count
        run: codespell --ignore-words=codespell.txt || exit 1
  misspell:
    name: Check spelling all files in commit with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: wget -O - -q https://raw.githubusercontent.com/client9/misspell/c0b55c8239520f6b5aa15a0207ca8b28027ba49e/install-misspell.sh | sh -s -- -b .
      - name: Misspell
        run: git ls-files --empty-directory | xargs ./misspell -i 'aircrafts,devels,invertions' -error
